name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Get release version
        run: echo ::set-env name=TAG_NAME::$(echo ${GITHUB_REF:10})
      - name: Install dependencies
        run: sudo apt-get install cmake pkg-config libssl-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Create release archive
        id: create_archive
        run: |
          DIST=syntaxdot-ffi-${TAG_NAME}-x86_64-linux-gnu-gcc
          ARCHIVE=${DIST}.tar.gz
          install -Dm755 -t ${DIST}/lib target/release/libsyntaxdot_ffi.so
          install -Dm644 -t ${DIST}/include include/syntaxdot.h
          install -Dm644 -t ${DIST}/share/syntaxdot/proto proto/syntaxdot.proto
          tar -czvf ${ARCHIVE} ${DIST}
          echo ::set-output name=ASSET::$ARCHIVE
      - uses: actions/create-release@v1.0.0
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.create_archive.outputs.ASSET }}
          asset_name: ${{ steps.create_archive.outputs.ASSET }}
          asset_content_type: application/gzip
